image: node:latest

stages:
  - build
  - deploy

cache:
  paths:
    - packages/signal/node_modules/
    - packages/web/node_modules/

variables:
  NODE_ENV: production

build-web:
  stage: build
  script:
    - cd packages/web
    - npm install --production=false
    - npm run build
    - rm build/static/**/*.map
  variables:
    REACT_APP_CONFIG_URL: /config.json
  artifacts:
    paths:
      - packages/web/build/
    expire_in: 10 minutes

build-signal:
  stage: build
  script:
    - cd packages/signal
    - npm install --production=false
    - npm run build
  artifacts:
    paths:
      - packages/signal/lib/
      - packages/signal/package.json
      - packages/signal/package-lock.json
    expire_in: 10 minutes


deploy-web:
  stage: deploy
  environment: live
  when: manual
  dependencies:
    - build-web
  before_script:
    - apt install awscli
  script:
    - aws s3 sync build $(WEB_BUCKET)
