image: node:latest

stages:
  - build
  - deploy

before_script:
  - apt-get update
  - apt-get install -y zip

cache:
  paths:
    - packages/signal/node_modules/
    - packages/web/node_modules/

variables:
  NODE_ENV: production

build-web:
  stage: build
  script:
    - cd packages/web
    - npm install --production=false
    - npm run build
  variables:
    REACT_APP_CONFIG_URL: /config.json
  artifacts:
    paths:
      - packages/web/build/
    expire_in: 10 minutes

build-signal:
  stage: build
  script:
    - cd packages/signal
    - npm install --production=false
    - npm run build
  artifacts:
    paths:
      - packages/signal/build/
    expire_in: 10 minutes


deploy-web:
  stage: deploy
  environment: live
  when: manual
  dependencies:
    - build-web
  before_script:
    - apt-get install awscli -y
  script:
    - npm run deploy
